---
AWSTemplateFormatVersion: '2010-09-09'
Description: Create azure ad parameters in ssm

Parameters:
  clientId:
    Description: The client app id
    Type: String
  clientSecret:
    Type: String
    Description: The client app secret value
    NoEcho: true
  tenantId:
    Type: String
    Description: The azure AD tenant id
  identityUrl:
    Type: String
    Description: IAM Identity Center issuer URL
  acsUrl:
    Type: String
    Description: IAM Identity Center Assertion Consumer Service (ACS) URL
  BucketName:
    Description: Bucket name to store the lambda zip code
    Type: String

Resources:
  S3Bucket: 
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref BucketName
  clientIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: clientId
      Type: String
      Value: !Ref clientId
      Description: Azure AD app client id
  clientSecretParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: clientSecret
      Type: String
      Value: !Ref clientSecret
      Description: Azure AD app secret value
  tenantIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: tenantId
      Type: String
      Value: !Ref tenantId
      Description: Azure AD tenant id
  identityUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: identityUrl
      Type: String
      Value: !Ref identityUrl
      Description: IAM Identity Center issuer URL
  acsUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: acsUrl
      Type: String
      Value: !Ref acsUrl
      Description: IAM Identity Center Assertion Consumer Service (ACS) URL

Outputs:
  S3BucketName:
    Description: S3 Bucket name to store the lambda zip code
    Value: !Ref S3Bucket
    Export:
      Name: !Sub ${AWS::StackName}-S3BucketName